# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jetbrains.kotlin.jvm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
